typedef unsigned int u32;
extern void delay_ms(u32 ms); 
extern void delay_sec(u32 sec);
extern void lcd8_data(unsigned char data); 
extern void lcd8_cmd(unsigned char cmd);
extern void lcd8_init(void);
extern void lcd4_data(unsigned char data);
extern void lcd4_cmd(unsigned char cmd);
extern void lcd4_init(void);
extern void lcd8_string(char *p);
extern void lcd4_string(unsigned char *p);
extern void lcd8_int(int num);
extern void lcd4_int(int num);
extern void lcd4_octal(int num);
extern void lcd4_hexa(int num);
extern void lcd8_octal(int num);
extern void lcd8_hexa(int num);
extern void lcd4_binary(int num);
extern void lcd4_float(float num);
extern void lcd8_binary(int num);
extern void lcd4_cgram(unsigned char *p);
extern void uart0_init(u32 baud);
extern void uart0_tx_data(unsigned char data);
extern void uart0_tx_string(unsigned char *p);
extern unsigned char uart0_rx_data(void);
extern void uart0_tx_integer(int num);
extern void uart0_tx_octal(int num);
extern void uart0_tx_hexa(int num);
extern void uart0_tx_float(float num);
extern void uart0_tx_binary(short int num);
//extern char * uart0_rx_string(void);
extern void adc_init(void);
extern unsigned int adc_read(unsigned char ch_num);
extern void uart0_rx_string(unsigned char *p,unsigned int len);
//extern unsigned char * uart0_rx_string(void);
extern unsigned char uart0_rx_data_home(void);
//extern void EINT3_ISR(void)__irq;
extern void config_eint2(void);
extern void config_vic_for_eint2(void);
extern void config_eint0(void);
extern void config_vic_for_eint0(void);
extern void config_uart0(void);
extern void config_vic_for_uart0(void);
extern void config_uart(void);
extern void config_vic_for_uart(void);
extern void config_rfid(void);
extern void config_vic_for_rfid(void);
extern void config_fiq(void);
extern void config_UART(void);
extern void config_vic_for_timer(void);
extern void config_timer(void);
extern void delays(unsigned int ms);
extern void config_sw1(void);
extern void config_sw2(void);
extern void config_sw3(void);
extern void config_vic_for_sw1(void);
extern void config_vic_for_sw2(void);
extern void config_vic_for_sw3(void);
extern void config_vic_for_rx(void);
extern void config_rx(void);
extern void spi0_init(void);
extern unsigned char spi0_transfer(unsigned char data);
extern unsigned short int mcp3204(unsigned char ch_num);
extern unsigned short int adc1_read(unsigned char ch_num);
extern void adc1_init(void);



